services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: django-web
    restart: always
    ports:
      - "8004:8004"
    # volumes: .:/app — production da olib tashlanishi kerak!
    # Chunki COPY . . bilan image ichida kod bor, volume uni ustiga yozadi
    # Faqat development uchun qoldiring:
    # volumes:
    #   - .:/app
    depends_on:
      db:
        condition: service_healthy   # DB tayyor bo'lgunga kut
    env_file:
      - .env

volumes:
  postgres_data: